import io
import logging
import smtplib
from email.mime.image import MIMEImage
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import pytz

from marketscanner import config
from marketscanner.strategies.base import Signal

log = logging.getLogger(__name__)

_ET = pytz.timezone(config.TIMEZONE)

# Direction badge colours
_DIR_COLOUR = {"UP": "#16a34a", "DOWN": "#dc2626"}
_DIR_ARROW  = {"UP": "▲", "DOWN": "▼"}


def _build_plain(signal: Signal, fired_et: str) -> str:
    lines = [
        f"Market:    {signal.market}",
        f"Strategy:  {signal.strategy}",
        f"Direction: {signal.direction}",
        f"Price:     {signal.price:.2f}",
        f"Time (ET): {fired_et}",
    ]
    if signal.box_top is not None:
        lines.append(f"Box top:   {signal.box_top:.2f}")
    if signal.box_bottom is not None:
        lines.append(f"Box bot:   {signal.box_bottom:.2f}")
    return "\n".join(lines)


def _build_html(signal: Signal, fired_et: str, has_chart: bool) -> str:
    colour = _DIR_COLOUR.get(signal.direction, "#6b7280")
    arrow  = _DIR_ARROW.get(signal.direction, "")

    rows = [
        ("Market",    signal.market),
        ("Strategy",  signal.strategy),
        ("Price",     f"{signal.price:.2f}"),
        ("Time (ET)", fired_et),
    ]
    if signal.box_top is not None:
        rows.append(("Box top", f"{signal.box_top:.2f}"))
    if signal.box_bottom is not None:
        rows.append(("Box bot", f"{signal.box_bottom:.2f}"))

    table_rows = "".join(
        f"<tr>"
        f'<td style="padding:4px 12px 4px 0;color:#6b7280;white-space:nowrap">{label}</td>'
        f'<td style="padding:4px 0;font-weight:600">{value}</td>'
        f"</tr>"
        for label, value in rows
    )

    chart_block = (
        '<p style="margin:20px 0 0">'
        '<img src="cid:chart" alt="chart" style="max-width:100%;border-radius:6px">'
        "</p>"
        if has_chart else ""
    )

    return f"""<!DOCTYPE html>
<html>
<body style="margin:0;padding:0;background:#f3f4f6;font-family:Arial,sans-serif">
<table width="100%" cellpadding="0" cellspacing="0" bgcolor="#f3f4f6">
  <tr><td align="center" style="padding:32px 16px">
    <table width="560" cellpadding="0" cellspacing="0"
           style="background:#ffffff;border-radius:8px;overflow:hidden;
                  box-shadow:0 1px 4px rgba(0,0,0,.12)">
      <!-- header -->
      <tr>
        <td style="background:{colour};padding:20px 24px">
          <span style="font-size:22px;font-weight:700;color:#fff">
            {arrow} {signal.market} {signal.direction} @ {signal.price:.2f}
          </span><br>
          <span style="font-size:13px;color:rgba(255,255,255,.85)">
            {signal.strategy} &mdash; MarketScanner
          </span>
        </td>
      </tr>
      <!-- body -->
      <tr>
        <td style="padding:24px">
          <table cellpadding="0" cellspacing="0" style="font-size:15px;color:#111">
            {table_rows}
          </table>
          {chart_block}
        </td>
      </tr>
      <!-- footer -->
      <tr>
        <td style="padding:12px 24px;background:#f9fafb;
                   font-size:11px;color:#9ca3af;border-top:1px solid #e5e7eb">
          Generated by MarketScanner &mdash; Opening Range Breakout strategy
        </td>
      </tr>
    </table>
  </td></tr>
</table>
</body>
</html>"""


def send_alert(signal: Signal, chart_figure=None) -> None:
    fired_et = signal.fired_at.astimezone(_ET).strftime("%Y-%m-%d %H:%M:%S %Z")
    subject = (
        f"[MarketScanner] {signal.market} {signal.strategy} "
        f"{signal.direction} @ {signal.price:.2f}"
    )

    cfg = config.EMAIL
    if not cfg["sender"] or not cfg["password"] or not cfg["recipient"]:
        log.warning("Email not configured — signal logged but not sent: %s", signal)
        return

    # Render chart PNG once (reused in both the HTML cid: reference and the
    # plain-attachment fallback kept for mail clients that strip HTML).
    chart_bytes: bytes | None = None
    if chart_figure is not None:
        buf = io.BytesIO()
        chart_figure.savefig(buf, format="png", bbox_inches="tight")
        chart_bytes = buf.getvalue()

    # Outer envelope: mixed (allows plain-attachment fallback for old clients)
    msg = MIMEMultipart("mixed")
    msg["Subject"] = subject
    msg["From"] = cfg["sender"]
    msg["To"] = cfg["recipient"]

    # related wraps html + inline image so cid: references resolve
    related = MIMEMultipart("related")

    # alternative: plain first, html last (clients pick the richest they support)
    alternative = MIMEMultipart("alternative")
    alternative.attach(MIMEText(_build_plain(signal, fired_et), "plain"))
    alternative.attach(MIMEText(_build_html(signal, fired_et, chart_bytes is not None), "html"))

    related.attach(alternative)

    if chart_bytes is not None:
        # Inline image referenced by cid:chart in the HTML
        cid_img = MIMEImage(chart_bytes, name="chart.png")
        cid_img.add_header("Content-ID", "<chart>")
        cid_img.add_header("Content-Disposition", "inline", filename="chart.png")
        related.attach(cid_img)

    msg.attach(related)

    try:
        with smtplib.SMTP(cfg["smtp_host"], cfg["smtp_port"]) as smtp:
            smtp.ehlo()
            smtp.starttls()
            smtp.login(cfg["sender"], cfg["password"])
            smtp.sendmail(cfg["sender"], cfg["recipient"], msg.as_string())
        log.info("Alert sent: %s", subject)
    except Exception as exc:
        log.error("Failed to send alert: %s", exc)
